
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps
    protocol: TCP
    port: 21
    targetPort: 21
  - name: ftps-send
    protocol: TCP
    port: 10100
    targetPort: 10100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
      app: ftps
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 21
        - containerPort: 10100